engine = " ENGINE=InnoDB"


dbName = "gmail"


dbQuery = "CREATE DATABASE IF NOT EXISTS "+dbName;


basic_query = "CREATE TABLE IF NOT EXISTS basic ( id INT PRIMARY KEY AUTO_INCREMENT, email_id VARCHAR(255) NOT NULL, pic VARCHAR(1000) DEFAULT NULL, name VARCHAR(100) NOT NULL, given_name VARCHAR(100) DEFAULT NULL, family_name VARCHAR(100) DEFAULT NULL, gender VARCHAR(10) DEFAULT 'male', gmail_id VARCHAR(100) NOT NULL, last_sync TIMESTAMP DEFAULT '1970-12-31 23:59:59', profile_details VARCHAR(1000) DEFAULT NULL, locale VARCHAR(50) DEFAULT 'en', verified_email VARCHAR(10) DEFAULT 'true', drive_folder_name TEXT DEFAULT NULL, drive_folder_id VARCHAR(255) DEFAULT NULL, drive_misc_folder_id VARCHAR(255) DEFAULT NULL, full_details TEXT DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP )"+engine


token_query = "CREATE TABLE IF NOT EXISTS token ( id INT PRIMARY KEY AUTO_INCREMENT, basic_id INT NOT NULL, token_details TEXT DEFAULT NULL, access_token VARCHAR(500) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP DEFAULT '1970-12-31 23:59:59', FOREIGN KEY (basic_id) REFERENCES basic(id) ON DELETE CASCADE )"+engine


mail_details_query = "CREATE TABLE IF NOT EXISTS mail_details ( id INT PRIMARY KEY AUTO_INCREMENT, basic_id INT NOT NULL, filter_id INT NOT NULL, mail_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, mail_from VARCHAR(200) NOT NULL, mail_id VARCHAR(200) NOT NULL, mail_subject VARCHAR(500) DEFAULT NULL, filename VARCHAR(500) DEFAULT NULL, attachment_id VARCHAR(500) NOT NULL, no_of_attachments INT DEFAULT '1', mime_type VARCHAR(200) DEFAULT NULL, drive_id VARCHAR(500) DEFAULT NULL, drive_path VARCHAR(1000) DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP DEFAULT '1970-12-31 23:59:59', FOREIGN KEY (basic_id) REFERENCES basic(id) ON DELETE CASCADE, FOREIGN KEY (filter_id) REFERENCES email_filter(id) ON DELETE CASCADE)"+engine


login_history_query = "CREATE TABLE IF NOT EXISTS login_history ( id INT PRIMARY KEY AUTO_INCREMENT, basic_id INT NOT NULL, filter_data TEXT DEFAULT NULL, filter_type TEXT DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (basic_id) REFERENCES basic(id) ON DELETE CASCADE )"+engine


email_filter_query = "CREATE TABLE IF NOT EXISTS email_filter ( id INT PRIMARY KEY AUTO_INCREMENT, basic_id INT NOT NULL, filter_data TEXT DEFAULT NULL, filter_type TEXT DEFAULT NULL, last_sync TIMESTAMP DEFAULT '1970-12-31 23:59:59', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (basic_id) REFERENCES basic(id) ON DELETE CASCADE )"+engine


drive_folders_query = "CREATE TABLE IF NOT EXISTS drive_folders ( id INT PRIMARY KEY AUTO_INCREMENT, basic_id INT NOT NULL, folder_name TEXT DEFAULT NULL, folder_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (basic_id) REFERENCES basic(id) ON DELETE CASCADE )"+engine